//Utilizando o try catch

try {
    const soma = x + y
}catch(error){
    console.log(`Erro no programa ${error}`)
}